### ISSUE TITLE
Collapsible arrow(caret) is not changing open/close state

### ISSUE THREAD

**Issue by Amitesh** [davidstutz/bootstrap-multiselect#1210]
In `enableCollapsibleOptGroups` option, the open/close caret is not changing it's state on the collapse of options below.

In below image we can see the caret state is same in open/close of group options.

<img width="214" alt="Screen Shot 2021-08-15 at 4 28 53 PM" src="https://user-images.githubusercontent.com/42645/129476188-c91f4f76-1f1a-4156-89e2-5f3bab46a171.png">

How we can align it with its state?

Thanks

**Comment by Amitesh** [comment]
I tried the below solution to fix it. 

```javascript
$(document).ready(function() {
  $('#example-enableCollapsibleOptGroups-new').multiselect({
    enableCollapsibleOptGroups: true
  });

  enhanceCollapsibleButton();
});

function enhanceCollapsibleButton() {
  $('#example-enableCollapsibleOptGroups-new').parent()
    .find('.multiselect-container .caret-container')
    .addClass('open');

  $('#example-enableCollapsibleOptGroups-new').parent()
    .find('.multiselect-container .caret-container')
    .click(function() {
      $(this).toggleClass('open close');
    });
}
```

Styles:
```css
.multiselect-container .caret-container {
  position: relative;
  cursor: pointer;
}

.multiselect-container .caret-container.open,
.multiselect-container .caret-container.close {
  float: none;
  height: initial;
  width: initial;
  font-size: 1rem;
  padding: 0px 8px;
}

.multiselect-container .caret-container::after {
  display: block;
  position: absolute;
  top: 50%;
  right: -4px;
  -webkit-transform: translateY(-50%) rotate(0deg);
  transform: translateY(-50%) rotate(0deg);
  font-size: 1rem;
  transition: transform 0.2s;
}

.multiselect-container .caret-container.close::after {
  -webkit-transform: translateY(-50%) rotate(-90deg);
  transform: translateY(-50%) rotate(-90deg);
}

```
Stackblitz url - [https://stackblitz.com/edit/bootstrap-multiselect-group-example](https://stackblitz.com/edit/bootstrap-multiselect-group-example)
